server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://pocketbase:8090/api/;
    }

    location /_/ {
        proxy_pass http://pocketbase:8090/_/;
    }
}
